# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sonar-pv-data
# spec:
#  storageClassName: standard
#  capacity:
#   storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#   path: "/mnt/data"
#  persistentVolumeReclaimPolicy: Retain

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi