apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonar-postgres
spec:
  serviceName: sonar-postgres
  replicas: 1
  selector:
    matchLabels:
      name: sonar-postgres
  template:
    metadata:
      name: sonar-postgres
      labels:
        name: sonar-postgres
    spec:
      containers:
        - image: postgres:12.1
          name: sonar-postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: POSTGRES_USER
              value: sonar
          readinessProbe:
           exec:
             command: ["pg_isready", "-U", "sonar", "-h", "0.0.0.0", "-p", "5432"]
           initialDelaySeconds: 35
           periodSeconds: 10
          livenessProbe:
           exec:
            command: ["pg_isready", "-U", "sonar", "-h", "0.0.0.0", "-p", "5432"]
           initialDelaySeconds: 35
           periodSeconds: 10
          resources:
            requests:
              memory: 1000Mi
              cpu: "250m"
            limits:
              memory: 2000Mi
              cpu: "500m" 
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            # This name must match the volumes.name below.
            - name: data-disk
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: claim-postgres